/** @format */

import { useRef } from "react";
import Head from "next/head";
import { Fade } from "react-reveal";
import { Contact, Hero, Intro, ProjectsSection } from "../components";

export default function Home() {
  const ref = useRef(null);

  const scrollToHero = () => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div>
      <Head>
        <title>Uzzam Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-full h-screen">
        <Fade bottom>
          <Intro scrollToHero={scrollToHero} />
        </Fade>
      </div>
      <div className="z-50 bg-gray-700">
        <div className="flex flex-col w-full h-auto">
          <Fade bottom>
            <Hero ref={ref} text="Testing" />
          </Fade>
        </div>

        <div className="flex flex-col w-full h-auto">
          <Fade bottom>
            <ProjectsSection />
          </Fade>
        </div>

        <div className="flex flex-col w-full h-auto">
          <Contact />
        </div>
      </div>
    </div>
  );
}
