/** @format */

import { useRef, useState } from "react";
import Head from "next/head";
import { Fade } from "react-reveal";
import {
  Contact,
  Hero,
  Intro,
  ProjectsSection,
  SkillsModal,
} from "../components";

export default function Home() {
  const ref = useRef(null);
  const homeRef = useRef(null);
  const projectsRef = useRef(null);
  const contactRef = useRef(null);

  // STATES
  const [showSkillModal, setShowSkillModal] = useState(false);

  // Change showModal state function
  const changeModalState = () => {
    setShowSkillModal(!showSkillModal);
  };

  // SCROLLS FUNCTIONS
  const scrollToHero = () => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  const scrollToHome = () => {
    homeRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const scrollToProjects = () => {
    projectsRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const scrollToContact = () => {
    contactRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div>
      <Head>
        <title>Uzzam Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showSkillModal && <SkillsModal changeModalState={changeModalState} />}
      <div className="flex flex-col items-center justify-center w-full h-screen">
        <Fade bottom>
          <Intro ref={homeRef} scrollToHero={scrollToHero} />
        </Fade>
      </div>
      <div className="z-50 bg-gray-700">
        <div className="flex flex-col w-full h-auto">
          <Fade bottom>
            <Hero
              ref={ref}
              text="Testing"
              scrollTo={scrollToHome}
              scrollToProjects={scrollToProjects}
              scrollToContact={scrollToContact}
              changeModalState={changeModalState}
            />
          </Fade>
        </div>

        <div className="flex flex-col w-full h-auto" ref={projectsRef}>
          <Fade bottom>
            <ProjectsSection />
          </Fade>
        </div>

        <div className="flex flex-col w-full h-auto" ref={contactRef}>
          <Contact />
        </div>
      </div>
    </div>
  );
}
